server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql.default.svc.cluster.local:3306/my_app_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
